Update Maroon Framework to wpilib 2023
Team766/MaroonFramework pull request #20
Opened 2023-01-15 23:16 UTC by dejabot

cherry-pick change from 2023 repo

2023-01-15 23:59 UTC, rcahoon requested changes

2023-01-15 23:59 UTC, rcahoon commented on src/main/java/com/team766/hal/wpilib/WPIRobotProvider.java
> +		return true;
Unless we need 2023 support immediately in other repos, I'd prefer to wait to upstream this until we have the implementation for this

2023-02-14 13:46 UTC, rcahoon requested changes

2023-02-14 13:46 UTC, rcahoon commented on src/main/java/com/team766/hal/wpilib/WPIRobotProvider.java
> +		if (digInputs[index] == null) {
bad merge here - lines are duplicated

2023-03-06 23:53 UTC, rcahoon approved these changes

2023-03-07 21:02 UTC, yongkimleng approved these changes

2023-03-11 06:24 UTC, merged